### ISSUE TITLE
Не запускаеться сам майн

### ISSUE THREAD

**Issue by red2211** [Dreamfinity/Dreamfinity-Tracker#101]
Лаунчер стартует нормально а вот сам майн нет. Стоит Ubuntu 20.04 и OracleJDK 8.
[лог.txt](https://github.com/Dreamfinity/Dreamfinity-Tracker/files/6215890/default.txt)

**Comment by Noire86** [comment]
udev зачем удалили?

**Comment by Noire86** [comment]
Проблему решили, теперь запуск пройдет нормально.
