### ISSUE TITLE
Краш при телепортации на /warp android

### ISSUE THREAD

**Issue by hohserg1** [Dreamfinity/Dreamfinity-Tracker#103]
**Информация (укажите соответствующие данные):**
 - Игровой ник: hohserg
 - Сервер: Spacecross

**Описание бага:**
Тп-ся на /warp android - крашнуло игру. Запустил заново - опять крашнуло.
Краш-репорт: https://pastebin.com/2kPWaEEB

**Воспроизведение:**
Шаги к воспроизведению бага:
1. Выполнить команду /warp android

**Ожидаемое поведение:**
Должно крашнуться

**Comment by Noire86** [comment]
Перекачайте клиент, должно помочь.
