### ISSUE TITLE
Невозможно скрафтить красный провод в оболочке

### ISSUE THREAD

**Issue by hohserg1** [Dreamfinity/Dreamfinity-Tracker#104]
**Информация (укажите соответствующие данные):**
 - Игровой ник: hohserg
 - Сервер: Spacecross

**Описание бага:**
Красный провод в оболочке крафтится из полосок дуба - микроблоков, которые запрещены. 
Сделайте этому проводу другой крафт.

**Воспроизведение:**
Шаги к воспроизведению бага:
1. Посмотреть рецепт в nei
2. Полоски дуба не крафтятся
3. Пилы не крафтятся

**Ожидаемое поведение:**
Можно было бы скрафтить этот провод и упростить некоторые редстоун-схемы

**Скриншоты:**
Если имеет смысл в конкретной ситуации, прикрепите скриншоты демонстрирующие суть бага.
![image](https://user-images.githubusercontent.com/35610168/113489701-51b62f00-94ce-11eb-9ac9-7c136982ede7.png)

**Comment by Noire86** [comment]
Микроблоки запрещены, но мы подумаем о введении отдельного рецепта
