### ISSUE TITLE
Небесные блоки в овере дают неправильный рендер

### ISSUE THREAD

**Issue by hohserg1** [Dreamfinity/Dreamfinity-Tracker#105]
**Информация (укажите соответствующие данные):**
 - Игровой ник: hohserg
 - Сервер: Spacecross

**Описание бага:**
Если в поле зрения будет находиться активный небесный блок, то вместо того, чтобы рендерить небо в пределах себя, он редерит небо во всех направлениях. Проявляется только в overworld, в других измерениях работает правильно.

**Воспроизведение:**
Шаги к воспроизведению бага:
1. Поставить инвертированный небесный блок
2. Увидеть это

**Ожидаемое поведение:**
Небесный блок должен рендерить небо в пределах своего хитбокса во всех измерениях

**Скриншоты:**
https://imgur.com/a/3AOAUhH

**Comment by Aizistral** [comment]
Разлогинься из матрицы

**Comment by hohserg1** [comment]
Чего?

**Comment by hohserg1** [comment]
Кажется, я нашел решение:
https://www.reddit.com/r/feedthebeast/comments/4k8jbh/infinity_evolved_skyblock_bug_inverted_sky_blocks/
По идее нужно запретить переключать эту настройку(чтобы не могли абузить для поиска небесных блоков)
