### ISSUE TITLE
Не крафтится апгрейд торговли

### ISSUE THREAD

**Issue by hohserg1** [Dreamfinity/Dreamfinity-Tracker#106]
**Информация (укажите соответствующие данные):**
 - Игровой ник: hohserg
 - Сервер: Spacecross

**Описание бага:**
Выкладываю рецепт апгрейда "торговля" из OpenComputers - результат не виден. Пробовал на разных верстаках. Пробовал крафтить из липкого поршня.

**Воспроизведение:**
Шаги к воспроизведению бага:
1. Выложите крафт
2. Результата крафта нет
4. Узрите!

**Ожидаемое поведение:**
Апгрейд должен крафтиться

**Скриншоты:**
Рецепт в неи:
![image](https://user-images.githubusercontent.com/35610168/113610410-c1a2f180-9655-11eb-9864-dfa2ed99bd69.png)
Попытка скрафтить: 
![image](https://user-images.githubusercontent.com/35610168/113610487-e008ed00-9655-11eb-89d0-11a09e4a84ce.png)

**Comment by DarkLorianPrime** [comment]
Если что-то не крафтится - в 99% случаев это креативное.
