### ISSUE TITLE
После смерти кнопки "Возродится" и "Главное меню" не работают

### ISSUE THREAD

**Issue by DaYundexTuxi** [Dreamfinity/Dreamfinity-Tracker#108]
**Информация:**
 - TheYundexTuxi 
 - Technocracy

**Описание бага:**
После смерти, кнопки не работают, т.е. нельзя не выйти с сервера не возродиться.

**Воспроизведение:**
Шагов нет, т.к. никак нельзя предугадать когда это случится.

**Ожидаемое поведение:**
Можно было бы нажать на кнопки и спокойно продолжить играть.

**Доп. информация:**
Ссылка на видео с багом:
https://drive.google.com/file/d/1JPYQr9i5e5Sv1QY2zGrIeYysNlXCfAUh/view?usp=sharing

**Comment by Veritaris** [comment]
Решено, закрыто
