### ISSUE TITLE
Крашит/кикает с серва некоторых игроков

### ISSUE THREAD

**Issue by DaYundexTuxi** [Dreamfinity/Dreamfinity-Tracker#109]
**Информация (укажите соответствующие данные):**
 - TheYundexTuxi
 - Технокарасик(Technocracy)

**Описание бага:**
Меня лично кикает с серва, kotofey51 так же кикает, хотя и крашнуло разок.

**Воспроизведение бага:**
Подлететь к заприваченным чанкам, фракция Mouse,  и тогда вылетаете с сервера, каждый раз когда перезаходите.
Зайти возможно только после перезапуска сервера и то на время, т.к. отгрузив и загрузив чанки, какое-то кол-во раз, всё равно выходит тот же баг.

**Ожидаемое поведение:**
Спокойная игра.

**Видео:**

https://drive.google.com/file/d/1FOubuUWz5vnJWsnkMzoiECP0RjseM0f_/view?usp=sharing (здесь вид из меню)

https://drive.google.com/file/d/1uhVJMbYx7iV7uIeeUX8H69H15PvkE1fx/view?usp=sharing (Вид кика)

**Дополнительный контекст:**
Перезаход/отключение Optifine не помогает.
В логах ничего, в отладке тоже.

**Comment by Noire86** [comment]
Нету файлов по ссылкам
