### ISSUE TITLE
Spacecross Warp bug

### ISSUE THREAD

**Issue by yokogami** [Dreamfinity/Dreamfinity-Tracker#112]
**Информация (укажите соответствующие данные):**
 - Игровой ник:  Megitsune
 - Сервер: SpaceCross

**Описание бага:**
Здесь должна быть чётко и понятно расписанная суть проблемы.
![image](https://user-images.githubusercontent.com/83757079/118366315-8aa2f280-b5a8-11eb-9846-04f28d1e3d4e.png)
Не выпускает из варпа, блоки которые оно блочит ломали, писало  мол теперь мешает другой блок.

**Ожидаемое поведение:**
Здесь опишите что, по вашему мнению, должно было случиться если бы бага не было (если есть необходимость).
Мы бы вошли в систему Кеплер

**Скриншоты:**
Если имеет смысл в конкретной ситуации, прикрепите скриншоты демонстрирующие суть бага.
![image](https://user-images.githubusercontent.com/83757079/118366374-9f7f8600-b5a8-11eb-864a-c25581a72c33.png)

**Comment by Noire86** [comment]
Проблему не решили?
