### ISSUE TITLE
Цифровиком можно ломать приватные блоки 

### ISSUE THREAD

**Issue by sashagavrilyuk** [Dreamfinity/Dreamfinity-Tracker#12]
Игровой ник: kotofey51

цифровик какого-то фига умеет ломать приватные вещи. 
Ломает блоки термалки. Ставишь ему нужный предмет "распространенная вещь тесеракт какого-то игрока" и он этот блок ломает. И ты потом можешь воровать энергию. 

Как : некоторые блоки цифровик не может сломать, знаю что он не может сломать, основа турелей. Добавить в каждый приватный блок свой анти ломатель цифровиком. 

Скриншоты: не дома.

Особые заметки: я уже так потерял много тесерактов

**Comment by sashagavrilyuk** [comment]
> Игровой ник: kotofey51
> 
> цифровик какого-то фига умеет ломать приватные вещи.
> Ломает блоки тетрадки. Ставишь ему нужный предмет "распространенная вещь тесеракт какого-то игрока" и он этот блок ломает. И ты потом можешь воровать энергию.
> 
> Как : некоторые блоки цифровик не может сломать, знаю что он не может сломать, основа турелей. Добавить в каждый приватный блок свой анти ломатель цифровиком.
> "Опишите, как должен работать та механика, которая вызывает баг или проблему"
> 
> Скриншоты: не дома.
> 
> Особые заметки: я уже так потерял много тесерактов

**Comment by DarkLorianPrime** [comment]
https://youtu.be/afyX__c5fiQ Подтверждено.

**Comment by DarkLorianPrime** [comment]
Пофикшено.

**Comment by Noire86** [comment]
Добавили блоки в блеклист.
