### ISSUE TITLE
Перестали работать персональные телепорты из RFTools

### ISSUE THREAD

**Issue by 1803** [Dreamfinity/Dreamfinity-Tracker#121]
**Информация (укажите соответствующие данные):**
 - Игровой ник: Yaphets
 - Сервер: Spacecross

**Описание бага:**
У меня поломались персональные телепорты (Charged Porter(#5487) и Matter Receiver (#1348)):
1. На корабле просто пропал блок телепорта. Я все еще могу туда полететь используя Advanced Charged Porter (#5469), но в полу дырка там где был телепорт
2. Портеры на планетах не работают: когда я на них лечу, меня выкидывает за пределы мира и я моментально умираю (буквально появляюсь мертвым)
3. Свежепоставленные портеры тоже не работают: только что поставил портер на корабле, улетел домой, при телепорте на него умер

Единственный рабочий портер из старых работает после 2 раз: Сначала портает куда-то около корабля, потом жму еще раз и меня кидает на корабль (на орбите одной из планет) 
Портер на земле (новый установлен для тестов) работает исправно.
Портер на орбите который работает сначала портает меня на координаты: x=5491 y=83 z=-10307. Это около 100к блоков от моего корабля. Там _ничего_ нет, я просто появляюсь в воздухе. Повторное использование отправляет меня на корабль

 
**Воспроизведение:**
Шаги к воспроизведению бага:
1. Установить Matter Receiver (#1348) на поверхности одной из планет
2. Привязать к нему Charged Porter(#5487) (Sneak+RMB)
3. Улететь обратно в World 0
4. Активировать Charged Porter(#5487) 
5. Умереть с сообщением "You've reached the world border" -> "x fell out of the world"

**Ожидаемое поведение:**
Еще утром все работало.

**Скриншоты:**
Не думаю что поможет.

**Дополнительный контекст:**
На сервере с утра были какие-то проблемы с телепортами со спавна. Было несколько перезагрузок с изменением каких-то настроек. Возможно связано.

**Comment by 1803** [comment]
Похоже проблема была в побочном эффекте обновления одного из модов. 
На данный момент проблема разрешена. Можно закрывать.

**Comment by TroubleDarkness** [comment]
Проблема решена. Тема закрыта.
