### ISSUE TITLE
Баги, баги, баги, баги

### ISSUE THREAD

**Issue by TroubleDarkness** [Dreamfinity/Dreamfinity-Tracker#122]
**Информация (укажите соответствующие данные):**
 - CrashBox
 - Mageweave + (все)

**Описание бага:**
- Нельзя создать части инструментов из Extra Tic. А точнее те, что добавляются из твайлайта. Если ты попробуешь их взять, они пропадут. (Mageweave)
- Не работает перчатка из Тинкера, которая должна увеличивать скорость копания, но не делает этого. (Mageweave)
- Отсутствует спавн странников края, адских гончих и скелетов-иссушителей в отведенных для них измерениях. (Mageweave)
- Приваты Factions не дают мобам (и нпц) наносить урон игроку, из-за чего невозможно создать данж. (все)

**Воспроизведение:**
Шаги к воспроизведению бага:
1. Сделайте то;
2. Сделайте это;
3. ...
4. Узрите!

**Ожидаемое поведение:**
Нормальная работа.

**Скриншоты:**
Нет таких.

**Дополнительный контекст:**
Чем быстрее это пофиксится - тем лучше.

**Comment by TroubleDarkness** [comment]
Новая проблема. Если сломать блок инструментом из "Тинкерс Констракт", созданным из террастали, то тебя выбросит из игры.

**Comment by Veritaris** [comment]
> Новая проблема. Если сломать блок инструментом из "Тинкерс Констракт", созданным из террастали, то тебя выбросит из игры.

Предоставьте, пожалуйста, краш-лог

**Comment by TroubleDarkness** [comment]
Игра не крашится. Выкидывает с сервера с сообщением "Internal Server Error"
