### ISSUE TITLE
Проблемы с голосованиями

### ISSUE THREAD

**Issue by AbelDigitalis** [Dreamfinity/Dreamfinity-Tracker#126]
**Информация.**
 - Игровой ник: Monlight
 - Сервер: Сайт

**Описание бага:**
Не засчитываются голоса на 2-х сайтах мониторинга серверов. 

**Воспроизведение:*
1.Проголосовать на MCTOP
2.Проголосовать на MCREATE
3.С обоих сайтов не засчитываются Шарды. 

**Ожидаемое поведение:**
Приход на аккаунт игрока 100 Шардов, а не 60 как сейчас. 

**Скриншоты:**
---

**Дополнительный контекст:**
Ощущение что проблема вызвана самими сайтами для мониторинга, но считаю что лучше донести эту информацию.

**Comment by Veritaris** [comment]
Добрый день. Да, к сожалению, в последнее время наблюдается проблема с взаимодействием сайтов для голосования и нашего сайта. Рассмотрим проблему в ближайшее время

**Comment by TroubleDarkness** [comment]
В данный момент проблема полностью исправлена.
