### ISSUE TITLE
Зашел в неправильно настроенный генератор щита из рф тулс и потерял все ресурсы и доступ к кораблю

### ISSUE THREAD

**Issue by oruggfjj** [Dreamfinity/Dreamfinity-Tracker#127]
**Информация (укажите соответствующие данные):**
 - Игровой ник: ItsNblbs
 - Сервер: Spacecross
 
**Описание потерянного:**
Все ресурсы и броння в инвентаре и телепортер на корабль

Список утраченного имущества:

**Обстоятельства потери:**
Опишите точное время и условия, при которых произошла потери вещи, корабля, или подобного.
9:0X
Я хотел поставить на корабль щит но неправильно настроил случайно зашел и умер а телепортер на корабль был в инвентаре

**Скриншоты:**
Приложите скриншоты, как доказательства того, что вы действительно имели эту вещь в собственности
![image](https://user-images.githubusercontent.com/63477897/178199046-67743b86-32fa-49f5-bcc2-f094cc458965.png)
![image](https://user-images.githubusercontent.com/63477897/178210375-90b71b8b-c431-45ba-81ee-d3f79651e880.png)
(там звезды закрашены)
![image](https://user-images.githubusercontent.com/63477897/178199145-983afee5-e0d3-499c-a6e5-cb5641e6b1a1.png)
![image](https://user-images.githubusercontent.com/63477897/178199847-1bec7e24-5f6d-4dcc-ab68-63fef3c52217.png)
И силовая броння была с плазменными щитами кулерами и джетпаком

**Дополнительный контекст:**

**Comment by oruggfjj** [comment]
что делать

**Comment by oruggfjj** [comment]
я не могу играть из за этого у меня ничего нет и я не могу попасть на корабль

**Comment by TroubleDarkness** [comment]
Здравствуйте. В ближайшие несколько минут можем найти и вернуть корабль вместе с самыми дорогими предметами из инвентаря. Для этого необходимо лишь его название и наличие вас на сервере.

UPD: Корабль найден. Ждём вас.
