### ISSUE TITLE
Телепортировался транспортером за границу мира и умер

### ISSUE THREAD

**Issue by oruggfjj** [Dreamfinity/Dreamfinity-Tracker#128]
**Информация (укажите соответствующие данные):**
 - Игровой ник: ItsNblbs
 - Сервер: Spacecross
 
**Описание потерянного:**
Здесь опишите, что было утрачено.

Список утраченного имущества:
Я не помню но весь инвентарь и броння

**Обстоятельства потери:**
12:XX
Я тестировал апи транспортера из Matter Overdrive и случайно телепортировался на нулевые координаты или что то вроде того и вот

**Скриншоты:**
![image](https://user-images.githubusercontent.com/63477897/178236391-0404162c-b9dc-4439-82c3-2fc7eea5d9e6.png)
Других нет

**Дополнительный контекст:**

**Comment by oruggfjj** [comment]
?

**Comment by oruggfjj** [comment]
????

**Comment by oruggfjj** [comment]
Что делать

**Comment by oruggfjj** [comment]
Я все ресурсы потерял

**Comment by oruggfjj** [comment]
???

**Comment by oruggfjj** [comment]
Помогите

**Comment by oruggfjj** [comment]
Что делать я все ресурсы потерял

**Comment by TroubleDarkness** [comment]
Здравствуйте. Если вы пишете о проблемах здесь - запаситесь терпением. Наш штат персонала сильно ограничен, из-за чего работать быстро и эффективно у нас не получается. Так же прошу заметить, что данный "чат" - не место для флуда сообщениями после описания основной проблемы. Вы вполне можете написать что-то новое в своей теме, если администрация в течение нескольких дней на него не реагирует, но это не значит, что вы должны флудить сообщениями с интервалом в несколько минут. Надеемся на понимание. 

С вашей проблемой в ближайшее время заберёмся.

**Comment by TroubleDarkness** [comment]
Здравствуйте. Мы установили деревянный сундук на вашей базе и сложили сохранившиеся вещи в него. Вполне возможно, что чего-то не хватает, но в этом мы не уверены.
![image](https://user-images.githubusercontent.com/33435797/178269774-7cdf460b-f79b-4b00-acd3-13d8a3cfcaaf.png)

**Comment by oruggfjj** [comment]
Спасибо
