### ISSUE TITLE
Ядро из Warp Drive не прыгает с квантовым мостом

### ISSUE THREAD

**Issue by oruggfjj** [Dreamfinity/Dreamfinity-Tracker#129]
**Информация (укажите соответствующие данные):**
 - Игровой ник: ItsNblbs
 - Сервер: Spacecross

**Описание бага:**
Корабль из Warp Drive не может прыгнуть если на нем стоит квантовый мост

**Воспроизведение:**
Шаги к воспроизведению бага:
1. Построить корабль
2. Построить на нем квантовый мост
3. ...
4. Узрите!

**Ожидаемое поведение:**
Корабль прыгнул бы

**Скриншоты:**
![image](https://user-images.githubusercontent.com/63477897/178370307-9ff3d87c-e13a-45a6-a59f-38d227779d75.png)
![image](https://user-images.githubusercontent.com/63477897/178370345-6a585d6b-7636-4335-8b00-40b46cd6e095.png)

**Дополнительный контекст:**
Здесь укажите любой дополнительный контекст, относящийся к проблеме, и/или ваши мысли о том в чём может быть её причина.

**Comment by TroubleDarkness** [comment]
Здравствуйте. Как мы понимаем, это не баг мода, а простая стенка, отделяющая игрока и сервер от какого-то крайне неприятного события в виде бага/краша и перманентной смерти. Блок квантового моста привязывается к другому через координаты и если при помощи Warp Drive попробовать перенести сам блок, то эти самые координаты уже никто не изменит, и это может привести к какой-либо ошибке.
