### ISSUE TITLE
Фазер на взрыв взрывает приватные блоки

### ISSUE THREAD

**Issue by sashagavrilyuk** [Dreamfinity/Dreamfinity-Tracker#13]
Игровой ник: kotofey51

Описание проблемы: фазер тоже может взрыватт приватные блоки.  Взрывает блоки мода меканизм (почти все блоки кроме цифровика), основа турелей и сейф из плотника. 

Просто берёшь и взрываешь.

Скриншоты: не дома.

Особые заметки: термалку он не может взорвать.

**Comment by DarkLorianPrime** [comment]
https://youtu.be/ki4V6VGvGcQ

**Comment by DarkLorianPrime** [comment]
Сейфы плотника тоже не ломаются. Закрыто.
