### ISSUE TITLE
Пропал корабль

### ISSUE THREAD

**Issue by oruggfjj** [Dreamfinity/Dreamfinity-Tracker#130]
**Информация (укажите соответствующие данные):**
 - Игровой ник: ItsNblbs
 - Сервер: Spacecross
 
**Описание потерянного:**
Корабль с 16 блоками варп изоляции тессерактом квантовым мостом и маскировщиком

Список утраченного имущества:
Весь корабль

**Обстоятельства потери:**
Незнаю я кодил какое то г кхм кхм поэтому не заходил 2 дня потом еще 2 вроде и я зашел сейчас пытаюсь телепортироватся на корабль телепортером из RfTools и пишет Something went wrong! The target has disappeared!

**Скриншоты:**
![image](https://user-images.githubusercontent.com/63477897/179347496-4978ac56-0c5c-4c44-ba8d-6111330d7c9e.png)
![image](https://user-images.githubusercontent.com/63477897/179347566-546775fd-0dec-476f-a3f2-3214b263cbf3.png)

**Дополнительный контекст:**
Здесь укажите любой дополнительный контекст, относящийся к проблеме, такие как доказательства, обоснования и/или ваши мысли о том, что могло быть причиной её возникновения.

**Comment by TroubleDarkness** [comment]
Здравствуйте, если вы считаете, что корабль именно пропал, а его не ограбили - напишите его название. В противном случае найти корабль будет почти невозможно.

**Comment by oruggfjj** [comment]
IMShip

**Comment by TroubleDarkness** [comment]
К сожалению, такого корабля не найдено. Вероятнее всего, за время вашего отсутствия он был разграблен.
![image](https://user-images.githubusercontent.com/33435797/179348575-075bf7ed-5f94-4fd7-82fe-fab3e1a516b1.png)

**Comment by oruggfjj** [comment]
Но там была изоляция щит из RfTools и маскировщик

**Comment by TroubleDarkness** [comment]
Это лишь средства, уменьшающие вероятность обнаружения корабля. Не более того. Так же была проверена призма и никаких действий на корабле не было найдено. Последние действия, записанные в логах ведут в пустое место, являющееся предполагаемым местонахождением корабля 4 дня назад. Никаких других записей найдено не было.

**Comment by Prodavec** [comment]
Полагаю эти последнии действия носили разрушительный характер. Если так, то корабль действительно ограбили и уничтожили.

**Comment by TroubleDarkness** [comment]
Говоря о "последних действиях" я подразумеваю действия самого ItsNblbs и последующий варп в другое место, в котором никаких логов уже нет.
