### ISSUE TITLE
Тритий из mekanism невозможно получить

### ISSUE THREAD

**Issue by oruggfjj** [Dreamfinity/Dreamfinity-Tracker#131]
**Информация (укажите соответствующие данные):**
 - Игровой ник: ItsNblbs
 - Сервер: Spacecross

**Описание бага:**
Тритий из mekanism невозможно получить потому что он делается из жидкого лития на солнечном активаторе нейтронов а жидкий литий в испарителе у которого нет крафта (мультиблок)

**Воспроизведение:**
Шаги к воспроизведению бага:
1. Погуглить как сделать тритий
2. Увидеть требование построить испаритель
3. ...
4. Узрите!

**Ожидаемое поведение:**
Здесь опишите что, по вашему мнению, должно было случиться если бы бага не было (если есть необходимость).

**Скриншоты:**
Если имеет смысл в конкретной ситуации, прикрепите скриншоты демонстрирующие суть бага.

**Дополнительный контекст:**
Здесь укажите любой дополнительный контекст, относящийся к проблеме, и/или ваши мысли о том в чём может быть её причина.

**Comment by Veritaris** [comment]
AFAIK тритий нужен только для термоядерного реактора, который также запрещён. По этой же причине запрещён мультиблочный испаритель

В данный момент все силы разработчиков направлены на другой сервер, однако не исключаю что после его открытия мы займёмся исправлением уже присутствующих на серверах модов чтобы открыть игрокам новый функционал и геймплей  

По вышеуказанной причине считаю логичным закрыть вопрос до момента начала работ по исправлению 
Приятной игры!

**Comment by oruggfjj** [comment]
Так тритием из Mekanism можно питать термоядерный реактор из NuclearCraft
