### ISSUE TITLE
Я умер на warp rq

### ISSUE THREAD

**Issue by oruggfjj** [Dreamfinity/Dreamfinity-Tracker#135]
**Информация (укажите соответствующие данные):**
 - Игровой ник: ItsNblbs
 - Сервер: Spacecross
 
**Описание потерянного:**
Все что было в инвентаре

Список утраченного имущества:
Все что было в инвентаре

**Обстоятельства потери:**
Не знаю точно у меня пропал интернет (я был на варпе rq) потом я зашел и был мертв

**Скриншоты:**
![image](https://user-images.githubusercontent.com/63477897/183029093-e56d101d-b06d-428f-bf86-d956c74d6905.png)

**Дополнительный контекст:**
Здесь укажите любой дополнительный контекст, относящийся к проблеме, такие как доказательства, обоснования и/или ваши мысли о том, что могло быть причиной её возникновения.

**Comment by TroubleDarkness** [comment]
В ближайшие несколько минут вернём. Наличие вас на сервере не требуется, при условии, если вам сейчас необходимо отойти.

Так же, в скором времени постараемся сделать так, чтобы на варпе нельзя было потерять вещи в принципе.

**Comment by TroubleDarkness** [comment]
Вещи вернули.
