### ISSUE TITLE
Черные кактусы

### ISSUE THREAD

**Issue by awe128** [Dreamfinity/Dreamfinity-Tracker#137]
### Информация (укажите соответствующие данные):   
 - Игровой ник: WhiteRabbit
 - Сервер: AF
 - Примерное время, когда возникла ошибка 14:09

### Описание бага:  
Мод Better Foliage чернит кактусы
![2022-09-16_14 04 53](https://user-images.githubusercontent.com/19672639/190626331-b6ec92c3-c067-4147-a2d1-5667fbfc5c78.png)
![2022-09-16_14 07 08](https://user-images.githubusercontent.com/19672639/190626336-72731ae2-e7fb-4877-b35a-9a34ee635627.png)

**Comment by TroubleDarkness** [comment]
Удалите клиент Arcanefactory. У вас используются старые настройки Better Foliage, в которых эта опция включена. Она  просто ужасно работает с кактусами. Удаление клиента рекомендуется сделать ВСЕМ. 

Если клиент не переустановить, возможны подобные казусы с другими модификациями и их конфигурационными файлами. Мы хотим, чтобы игра выглядела прилично.

**Comment by awe128** [comment]
Спасибо
