### ISSUE TITLE
Косметическое предложение

### ISSUE THREAD

**Issue by awe128** [Dreamfinity/Dreamfinity-Tracker#141]
**Информация:**
 - Игровой ник: WhiteRabbit
 - Сервер: AF
 
**Описание предложения:**
Немного смягчить края элементов   @@HUD`a
![image](https://user-images.githubusercontent.com/19672639/190672493-834e78f5-8312-46dc-a29e-322c4c57ffa9.png)

**Обоснование:**
Не будет "резать" глаз

**Comment by Veritaris** [comment]
Не совсем понял что именно смягчать 
Не могли бы вы уточнить

**Comment by vertexofvortex** [comment]
Осмелюсь предположить, человек имеет в виду использовать полупрозрачность на скруглениях, дабы они выглядели менее пиксельно. Однако я здесь не за этим.

Раз уж поднялась тема косметических улучшений, то интерфейс этого HUDа весьма не интуитивен. Например, я до сих пор не представляю, что это за полоска, которая вторая по счёту. Также не совсем очевидно с первого взгляда, что эти коричневые кружочки — индикатор голода. Предлагаю сделать что-то вроде такого:

![Screenshot from 2022-09-16 22-33-40](https://user-images.githubusercontent.com/31506708/190716870-7fedb575-129c-4dc8-9785-4d70ac9d63f4.png)
_(иконки голода нарисованы на коленке, скругления барам было делать лень)_

Сразу понятно что и где благодаря иконкам. Сильно маленькими их, конечно не сделать, в силу того, что интерфейс сам по себе небольшой (бтв на этой панели гектары неиспользованного пространства, которое можно занять функциональными компонентами), однако прикреплённая мной картинка всего лишь пример того, каким этот HUD вижу я.

**Comment by Veritaris** [comment]
Будет изменено в ближайшем обновлении
