### ISSUE TITLE
Не крафтится теплопровод из IC2

### ISSUE THREAD

**Issue by vertexofvortex** [Dreamfinity/Dreamfinity-Tracker#148]
### Информация (укажите соответствующие данные):   
 - Игровой ник: vrtx + мой друг и соратник IDDQD, который этот баг и нашёл
 - Сервер: AF
 - Примерное время, когда возникла ошибка: always has been (23:21)

### Описание бага:  
Ошибка в рецепте теплопровода (ID 4132:5). Одна из пластин обязательно должна быть из иммёрсива, а пластина из иммёрсива не имеет крафта. Дальнейшее развитие по моду не представляется возможным.

### Воспроизведение:  
STEP 1: откройте верстак
STEP 2: попробуйте скрафтить указанный выше предмет
STEP 3: cover yourself in oil

### Скриншоты:  
![image](https://user-images.githubusercontent.com/31506708/190726826-5edd5a58-99b4-476c-b382-2b272fd87e6e.png)

Записал видео, доступно по ссылке: https://youtu.be/FOJxwE1oZJs.

**Comment by TroubleDarkness** [comment]
Исправлено.
