### ISSUE TITLE
Проблема с чанками (НЕ КОТ)

### ISSUE THREAD

**Issue by DarkLorianPrime** [Dreamfinity/Dreamfinity-Tracker#15]
**Информация (укажите соответствующие данные):**
 - Игровой ник: D_Lorian
 - Сервер: Magewave (мб все)

**Описание бага:**
При переезде на новый хост, сбились настройки приватов. Не выдаются чанки при повышении рангов.

**Воспроизведение:**
Шаги к воспроизведению бага:
1. зайдите на магию
2. копайте землю
3. ...
4. Узрите! на 70 ранге у вас 2 чанка

**Ожидаемое поведение:**
ну, на 70 ранге как минимум 12 чанков

**Comment by Noire86** [comment]
Починено
