### ISSUE TITLE
Автозаполнение крафта

### ISSUE THREAD

**Issue by johnyheinz** [Dreamfinity/Dreamfinity-Tracker#154]
### Информация (укажите соответствующие данные):   
 - Игровой ник: IDDQD

### Описание бага:  
не работает автозаполнение крафта, если в рецепте есть хотя бы один предмет с прочностью (да также касается и заряжаемых предметов)

### Воспроизведение:  

1. возьмите любой рецепт для крафта, в котором есть шмотка с прочностью (например жидкостную помпу из термала)
2. подготовьте все вещи для крафта
3. shift+лкм по вопросу
4. ??????????????????
5. ничего не произошло

### Ожидаемое поведение:  
автозаполнение крафта вне зависимости от прочности предметов

### Скриншоты:  
![изображение](https://user-images.githubusercontent.com/74152968/190899303-96c0ebdb-0fe3-4e82-aed5-7dd69167a093.png)
![изображение](https://user-images.githubusercontent.com/74152968/190899311-57dd3d1a-9e59-4f44-ae40-e8ce901e83f2.png)

**Comment by TroubleDarkness** [comment]
Здравствуйте. Данная "фича" была отключена исключительно из-за того, что с ней были связаны некоторые баги с дубликацией (дюпом) предметов. Если появится возможность исправить проблемы - мы обязательно это сделаем для удобства игроков. В следующий раз попробуйте быть менее токсичными при взаимодействии с администрацией. Если вам известно что-то, чего не знаем мы, это не значит, что у нас нет права попытаться узнать это у вас. В некоторых случаях это может серьёзно сокращать время решения проблемы.
