### ISSUE TITLE
сбрасываются настройки модулярки 

### ISSUE THREAD

**Issue by sashagavrilyuk** [Dreamfinity/Dreamfinity-Tracker#16]
**Информация (укажите соответствующие данные):**
 - Игровой ник: kotofey51
 - Сервер: spacecross

**Описание бага:**
почему то все вечно сбрасываются настройки модулярки. и все вечно приходиться заходить в верстак что бы они вновь появилось.

**Воспроизведение:**
Шаги к воспроизведению бага:
1. зайти в майн
2. зайти на серв
3. Узрите!

**Ожидаемое поведение:**
добавить конфиг на не забрасывание 

**Скриншоты:**
до перезахода
![unknown](https://user-images.githubusercontent.com/38777263/101067306-11868480-35a0-11eb-95c7-69e19e90fadb.png)
после перезахода
![unknown](https://user-images.githubusercontent.com/38777263/101067381-28c57200-35a0-11eb-9e48-fce80ac7437a.png)

**Дополнительный контекст:**
если что я не ставлю еще раз бинды. мне просто надо зайти в верстак потом в настройки и они сразу же все появляются.

**Comment by Noire86** [comment]
Сделал кое-что, проверьте сброс настроек

**Comment by Noire86** [comment]
Сброс настроек - проблема конфликтующих кейбиндов, а не перекачки конфигов. Закрыто.

**Comment by DarkLorianPrime** [comment]
Для решения данной проблемы перекачайте клиент.
