### ISSUE TITLE
Тултипы для забаненных предметов

### ISSUE THREAD

**Issue by vertexofvortex** [Dreamfinity/Dreamfinity-Tracker#165]
**Информация (укажите соответствующие данные):**
 - Игровой ник: vrtx
 - Сервер: все
 
**Описание предложения:**
Добавить для забаненных предметов в тултипе (описании) строчку о том, что данный предмет нельзя использовать. Это позволит избежать подобных ситуаций:

![image](https://user-images.githubusercontent.com/31506708/194382615-88bcf26a-41be-439f-8cff-9f096a12801b.png)

Помимо этого, я бы предложил вам хранить список забаненных предметов в одном месте для устранения его рассинхрона в разных местах. Например, если бан происходит при помощи плагина, можно написать скрипт, который будет считывать данный список из конфига с некой периодичностью, автоматически отсылать запрос CMS для обновления его на сайте, и перезаписывать конфиг мода, который ответственный за добавление тултипов (если кнш это будет происходить при помощи мода). Вообще, я понятия не имею, как это у вас всё реализовано, поэтому тут уж сами додумайте. В теории, я бы даже мог помочь написать этот скрипт.

**Comment by TroubleDarkness** [comment]
Здравствуйте!

О добавлении тултипов, информирующих игрока о том, что предмет находится в бане уже долгое время ходят легенды. Это очень классная, но почему-то до сих пор нереализованная на проекте идея, о которой множество раз писал даже я. Надеюсь, кто-нибудь и когда-нибудь увидит эти сообщения и что-нибудь сделает с этим.

Список заблокированных предметов и так хранится в одном списке как для сервера, так и для сайта, только по какой-то причине, человек, имеющий к нему (сайту) доступ, максимально сильно не хочет его синхронизировать. Предполагаю, что совершить несколько действий невероятно сложно.

**Comment by vertexofvortex** [comment]
> Здравствуйте!
> 
> О добавлении тултипов, информирующих игрока о том, что предмет находится в бане уже долгое время ходят легенды. Это очень классная, но почему-то до сих пор нереализованная на проекте идея, о которой множество раз писал даже я. Надеюсь, кто-нибудь и когда-нибудь увидит эти сообщения и что-нибудь сделает с этим.
> 
> Список заблокированных предметов и так хранится в одном списке как для сервера, так и для сайта, только по какой-то причине, человек, имеющий к нему (сайту) доступ, максимально сильно не хочет его синхронизировать. Предполагаю, что совершить несколько действий невероятно сложно.

Этим человеком был Олег Глуховский.

**Comment by Veritaris** [comment]
Был добавлен внутриигровой тултип для забаненных предметов 
Закрыто
