### ISSUE TITLE
Команды

### ISSUE THREAD

**Issue by Virus-33** [Dreamfinity/Dreamfinity-Tracker#169]
**Информация (укажите соответствующие данные):**
 - Игровой ник: Camerman
 - Сервер: все
 
**Описание предложения:**
Добавить клоны команд на русской раскладке

**Обоснование:**
Думаю было бы неплохо, если бы можно было вводить команды в чат, не запариваясь с раскладкой, которая меняется после каждого сообщения/поиска в NEI

**Comment by Veritaris** [comment]
Не имеет смысла
Закрыто
