### ISSUE TITLE
Сломал сервер (опять)

### ISSUE THREAD

**Issue by IFlyingTea** [Dreamfinity/Dreamfinity-Tracker#17]
- Игровой ник: IFlyingTea
 - Сервер: Spacecross

Поставил в транспортер из matter overdrive слишком большие числа и сломал серв

Шаги к воспроизведению бага:
1. Поставить транспортер из matter overdrive и подключить к нему компьютер из opencomputers
2. Сделать программу, которая будет вводить в  транспортер координаты
3. Вести по трем осям " 2 147 483 647"
4. Получаем зависание майна и падения сервера при перезаходе

![image](https://user-images.githubusercontent.com/75455153/101098944-dbafc300-35d4-11eb-908f-1e3ac369e46e.png)

**Comment by Noire86** [comment]
Фиксед.
