### ISSUE TITLE
босс на сатурне крашит сервер

### ISSUE THREAD

**Issue by sashagavrilyuk** [Dreamfinity/Dreamfinity-Tracker#18]
**Информация (укажите соответствующие данные):**
 - Игровой ник: kotofey51
 - Сервер: Spacecross

**Описание бага:**
на сатурне есть босс гаст который своим появлением крашит серв. получается сатурн ни как не пройти и ракету 5 уровеня там не достать.

**Воспроизведение:**
Шаги к воспроизведению бага:
1. зайти к босовой комнате
2. выйти из босовой комнатой
3. и повторять пока серв не сдохнет
4. узрите!

**Ожидаемое поведение:**
выпилить его к чертям собачьем и сделать все сундуки на сатурне открытыми. 

**Скриншоты:**
не нужен

**Дополнительный контекст:**
не нужно

**Comment by Noire86** [comment]
Необходимо проверить заново

**Comment by Noire86** [comment]
Исправлено
