### ISSUE TITLE
Noire, все еще, не удалил проект

### ISSUE THREAD

**Issue by mayakplay** [Dreamfinity/Dreamfinity-Tracker#19]
**Информация (укажите соответствующие данные):**
 - Игровой ник: noire
 - Сервер: any

**Описание бага:**
Noire, все еще, не удалил проект

**Воспроизведение:**
Noire, все еще, не удалил проект

**Ожидаемое поведение:**
Noire, все еще, не удалил проект

**Скриншоты:**
Noire, все еще, не удалил проект

**Дополнительный контекст:**
Noire, все еще, не удалил проект

**Comment by Noire86** [comment]
/delete perdakovsky 

Fixed.
