### ISSUE TITLE
Бан лилий края

### ISSUE THREAD

**Issue by DarkLorianPrime** [Dreamfinity/Dreamfinity-Tracker#20]
**Информация (укажите соответствующие данные):**
 - Игровой ник: Лор
 - Сервер: Магия

**Описание бага:**
Лилии Края флудят эндерменами и залагивают сервер

**Воспроизведение:**
Шаги к воспроизведению бага:
1. поставьте лилию
2. подождите
3. ...
4. Убейте спавн мобов в мире!

**Ожидаемое поведение:**
Здесь опишите что, по вашему мнению, должно было случиться если бы бага не было (если есть необходимость).

**Скриншоты:**
Если имеет смысл в конкретной ситуации, прикрепите скриншоты демонстрирующие суть бага.

**Дополнительный контекст:**
Здесь укажите любой дополнительный контекст, относящийся к проблеме, и/или ваши мысли о том в чём может быть её причина.

**Comment by DarkLorianPrime** [comment]
ids = 1889 и 1889:15

**Comment by Noire86** [comment]
Fixed
