### ISSUE TITLE
умение лесоруба отделили красный цвет

### ISSUE THREAD

**Issue by sashagavrilyuk** [Dreamfinity/Dreamfinity-Tracker#22]
**Информация (укажите соответствующие данные):**
 - Игровой ник: Kotofey51
 - Сервер: Technocracy

**Описание бага:**
умение лесоруба отделили красный цвет

**Воспроизведение:**
Шаги к воспроизведению бага:
1. активировать лесоруба
2. подождать
3. и выйдет это

**Ожидаемое поведение:**
сделать нормальный красный цвет

**Скриншоты:**
![image](https://user-images.githubusercontent.com/38777263/101594775-ea461200-39fa-11eb-99e1-2ab35f62b3ba.png)

**Дополнительный контекст:**
нету

**Comment by Noire86** [comment]
fixed
