### ISSUE TITLE
краном из опен блока можно таскать людей и нпс 

### ISSUE THREAD

**Issue by sashagavrilyuk** [Dreamfinity/Dreamfinity-Tracker#24]
**Информация (укажите соответствующие данные):**
 - Игровой ник: kotofey51
 - Сервер: Technocracy

**Описание бага**
можно выносить людей за приватом и пиздить их и тоже самое с мобами и нпс

**Воспроизведение:**
Шаги к воспроизведению бага:
1. одеть кран
2. юзнуть пульт
3. и поднять моба или человека
4. Узрите!

**Ожидаемое поведение:**
просто вырежьте это и все и так что бы нельзя было скрафтить для крана части 

**Скриншоты:**
![image](https://user-images.githubusercontent.com/38777263/101669928-3aed5780-3a5b-11eb-85e6-0d929e81dbf5.png)

**Дополнительный контекст:**
нету

**Comment by Noire86** [comment]
Пофикшено
