### ISSUE TITLE
Баг внутриигрового магазина

### ISSUE THREAD

**Issue by IFlyingTea** [Dreamfinity/Dreamfinity-Tracker#26]
- Игровой ник: IFlyingTea
 - Сервер: Spacecross

Поехала вкладка внутриигрового магазина с донатами

![image](https://user-images.githubusercontent.com/75455153/101807684-73a63300-3b26-11eb-82a8-8b5d35671d0e.png)

**Comment by Noire86** [comment]
Должно работать корректно в фуллскрине.
