### ISSUE TITLE
So apparently all of my stuff is gone, and i don't know what happened.

### ISSUE THREAD

**Issue by Alphabetosis** [Dreamfinity/Dreamfinity-Tracker#27]
**Информация (укажите соответствующие данные):**
 - Игровой ник:  Mortar
 - Сервер: Technocracy
 
**Описание потерянного:**
I don't really know what happened, so i'll deconstruct everything from the moment i left my loot unsupervised. I tp'd to spawn in order to travel to giant forest biome (i don't know how's it named, sry) on the east of the map. Sadly, i died to a poison, so i respawned at the spawn and travelled back home via /f home. However, as soon as i teleported i noticed everything from my chests and furnaces is gone, and by everything i mean EVERYTHING, even the trashiest things of all disappeared. What really frustrates me is that i've lost a dragon egg and a shit ton of resources, including 2 irradium ingots, 20 diamonds, 33 chrysocite crystals and a few stacks of tin, copper and other materials. There're also a molecular transformer and an ultima solar panel at my home but they were untouched, which really gets me curious of what have happened to my chests.

Список утраченного имущества:
1. dragon egg
2. 2 irradium ingots
3. ~2.5 stacks of copper
4. 33 chrysocite crystals
5. ~4 stacks of tin
6. ~64 of eternium crystals
7. 21 energium dust
8. staff of traveling
9. some minor stuff that i can live without

**Обстоятельства потери:**
As i said, i wasn't looking after my chests when this occured and i don't really know what exactly had occured, but when i came back home every block that had an item buffer was completely empty, every chest and furnace. All of them were under a /f claim region lock, so it's not my stupidity which had caused it. A molecual transofrmer, an ultimate solar panel, 2 generators and a macerator were unharmed and even kept their enegry buffers.

**Скриншоты:**
I can't really give any proof of what i had, i simply wasn't expecting something like this to happen, so all i can show you is the emptiness of my chests that once were filled with loot. Some of my activity must've been logged though, so i believe you can check it out and probably find some evidence.
![Desktop Screenshot 2020 12 11 - 00 03 55 88](https://user-images.githubusercontent.com/75814623/101841496-11195b00-3b57-11eb-89a6-12d0afd623eb.png)

**Дополнительный контекст:**
As far as i believe, it's somewhat of a unfortunate bug and not a mastermind robbery. I've encountered some other bugs on this server before (the most ridiculous one was with the all-command mute, when /f home was the only method i could tp or write anything), so i won't be suprised if that's another glitch that happened. I understand that the amount of proof i've presented is the definition of "little to none", but trust me, it's not that i would try to fool someone for a couple stacks of ingots and a staff from dungeons, it's the dragon egg and the amount of time i've spent fighting for it and looking for chrysocite afterwards that really matters to me. I certainly hope that atleast SOME proof can be found in logs.

**Comment by Extegral** [comment]
Я вот только не пойму чего ты на английском всё расписал, хотя ну, русский явно знаешь, иначе дорогу до данного ишшуй трекера не нашёл бы. Это такой экскуизит ориджинал тач?

**Comment by Alphabetosis** [comment]
> Я вот только не пойму чего ты на английском всё расписал, хотя ну, русский явно знаешь, иначе дорогу до данного баг-трекера не нашёл бы. Это такой экскуизит ориджинал тач?

I was recommended to go here by another player and it wouldn't be possible for me to navigate here without constant translation, the fact that i ended up here is not necessarily because i know any of russian c: .

**Comment by Extegral** [comment]
How the hell you even ended up on Dreamfinity in the first place then?

**Comment by Alphabetosis** [comment]
I mean, it's not THAT hard for me to turn VPN on, it gets me preety low latency and on top of that, i really like the combination of mods this server has created. Every item is translated into english or my native language so that is not a problem, too. Troubles connecting with other players happen occasionally, but there are very few, especially comparing to the amount of people that do know english on somewhat speakable level.

**Comment by Noire86** [comment]
Wow, thats a rare bean out there. Sure we can get your items back, just for exception, as long as you are the first english-speaking player. A s far as I can remember :D :pog:

**Comment by Alphabetosis** [comment]
Thank you! I'm honestly suprised that i am the first person to not speak russian fluently on this server, maybe i should learn it just a little bit so that i can talk on a basic level and not make it a harder time for everyone else.

**Comment by DarkLorianPrime** [comment]
Hi! I gave you your things back, put the door up, it will protect you. Just found bug-users. Fix it. I gave you a couple of griefer's things, because he didn't do it fair.
