### ISSUE TITLE
Кикает с сервера при открытии вкладки с кейсами в донат-магазине 

### ISSUE THREAD

**Issue by vhizu** [Dreamfinity/Dreamfinity-Tracker#30]
**Информация (укажите соответствующие данные):**
 - Игровой ник: vhizu
 - Сервер: Technocracy

**Описание бага:**
Кикает с сервера при открытии вкладки с кейсами в донат-магазине.

**Воспроизведение:**
Шаги к воспроизведению бага:  
1. Открыть донат магазин.
2. Открыть вкладку с кесами.
3. ...
4. Узрите! Вас кикнуло с сервера.

**Ожидаемое поведение:**
Должны быть показаны кейсы, либо просто вырезать эту фичу.

**Comment by Noire86** [comment]
Проблема решена.
