### ISSUE TITLE
HD скины

### ISSUE THREAD

**Issue by DarkLorianPrime** [Dreamfinity/Dreamfinity-Tracker#32]
**Информация (укажите соответствующие данные):**
 - Игровой ник:  лор
 - Сервер: все

**Описание бага:**
Не работают HD скины

**Comment by Noire86** [comment]
UPD: Cкины работают на Mageweave

Нужно выявить конфликтующий мод.

**Comment by Noire86** [comment]
Наконец-то пофикшено
