### ISSUE TITLE
Правила на сервере Дискорд

### ISSUE THREAD

**Issue by IFlyingTea** [Dreamfinity/Dreamfinity-Tracker#33]
- Игровой ник: IFlyingTea
 - Сервер: Не имеет значения
 
Хотелось бы увидеть на сервере Дискорд канал с правилами этого же сервера

Правила нужны хотя бы для того, чтобы официально кикать и банить особо навязчивых игроков из Дискорда

**Comment by DarkLorianPrime** [comment]
на новом сервере дримфинити есть правила.
