### ISSUE TITLE
меня забанили за гриферство хотя я не причастен

### ISSUE THREAD

**Issue by Dimariiik** [Dreamfinity/Dreamfinity-Tracker#34]
**Информация (укажите соответствующие данные):**
 - Игровой ник: 
 - Сервер:
 
**Описание предложения:**
Чётко изложите суть и смысл вашего предложения

**Обоснование:**
Опишите, почему вы хотели бы видеть предложенные измененения или нововведения добавленными на проект (если есть причины).

**Comment by DarkLorianPrime** [comment]
пустой запрос.
