### ISSUE TITLE
Сделать что-то с имбовостью Экскалибура

### ISSUE THREAD

**Issue by DarkLorianPrime** [Dreamfinity/Dreamfinity-Tracker#5]
Стоит относительно дешево, а выносит так, что защиты от него ПРАКТИЧЕСКИ не существует.

**Comment by Veritaris** [comment]
Экскалибур удалён из магазина. В ближайшую неделю будет убран из игры, игрокам с ним будет выдана соответствующая компенсация в шардах

**Comment by Extegral** [comment]
Экскалибур и Реликвия Хаоса выпилены из специально обученного апдейта архитектурного аддона. Осталось только чтобы эта версия оказалась на серверах.
