### ISSUE TITLE
Kubuntu + dreamprotect = краш

### ISSUE THREAD

**Issue by HBEunit** [Dreamfinity/Dreamfinity-Tracker#56]
**Информация (укажите соответствующие данные):**
 - Игровой ник: HBEunit (не имеет значения)
 - Сервер: Spacecross (не имеет значения)
- Операционная система: Kubuntu 20.10
- Версия KDE Plasma: 5.19.5
- Версия KDE Frameworks: 5.74.0
- Версия Qt: 5.14.2
- Версия ядра: 5.4.0-51-generic
- Архитектура: 64-битная
- Память: 7,7 ГиБ ОЗУ
- Среда выполнения Java: OpenJDK версий 8 и 11, OracleJDK 1.8.0_251 и OracleJRE 1.8.0_271

**Описание бага:**
Клиент Minecraft аварийно завершает работу примерно на 11% запуска, натыкаясь на мод DreamProtect

**Воспроизведение:**
Шаги к воспроизведению бага:
1. Выбрать необходимую среду исполнения
```
hbeunit@kubuntu:/usr/lib/jvm$ sudo update-alternatives --config java
Есть 4 варианта для альтернативы java (предоставляет /usr/bin/java).

  Выбор   Путь                                        Приор Состояние
------------------------------------------------------------
...
* 4            /usr/lib/jvm/jre1.8.0_271/bin/java               1         ручной режим

Press <enter> to keep the current choice[*], or type selection number: 4
```
2. Проверить, что JRE совместима с x64
```
hbeunit@kubuntu:/usr/lib/jvm$ java -d64 -version
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
```
3. Обьяснить системе, что ява запускается через /usr/bin/java
4. Запустить клиент с 2048 МБ оперативной памяти

**Ожидаемое поведение:**
Клиент запускается без проблем

**Скриншоты:**
Если имеет смысл в конкретной ситуации, прикрепите скриншоты демонстрирующие суть бага.

**Дополнительный контекст:**
[Краш-репорт](https://pastebin.com/XE71PvHU)

Кусочек краш-репорта
```
java.lang.NullPointerException: Initializing game
	at java.security.MessageDigest.update(MessageDigest.java:338)
	at java.security.MessageDigest.digest(MessageDigest.java:413)
	at org.apache.commons.codec.digest.DigestUtils.sha1(DigestUtils.java:466)
	at org.apache.commons.codec.digest.DigestUtils.sha1(DigestUtils.java:491)
	at org.apache.commons.codec.digest.DigestUtils.sha1Hex(DigestUtils.java:529)
	at ru.sceri.mods.dreamprotect.a.a(a.java) <-- Внимание сюда
```
Скорее всего виноват мод dreamprotect. Эта ошибка происходит независимо от выбора среды выполнения.

**Comment by Noire86** [comment]
Всегда нормально запускается на пинуксах всех мастей, почему у вас не работает - очень странно.

Либо пробуйте другой дистриб, либо как-то делать одну JRE или JDK в системе

Что там с Kubuntu понятия не имею.

Если проблема останется на свежей убунте, например - переоткройте таск.

**Comment by HBEunit** [comment]
Я переустановил систему с LVM. Да, это еще кубунта, но JVM кросс-платформенная, так что отличий в диструбтивах нет.
Установил всего одну яву - JDK версии ``1.8.0_281`` (JDK включает в себя JRE той же версии; это последняя доступная версия на момент проверок),
```
HBEunit@kubuntu:~/.minecraftlauncher/Dreamfinity/updates/Spacecross/mods/1.7.10$ sudo update-alternatives --query java
Name: java
Link: /usr/bin/java
Status: manual
Best: /usr/local/lib/jdk1.8.0_281/bin/java
Value: /usr/local/lib/jdk1.8.0_281/bin/java

Alternative: /usr/local/lib/jdk1.8.0_281/bin/java
Priority: 20
```
Я решил посмотреть в код и краш-репорт. Из репорта понятно, что ошибка началась с ``ru.sceri.mods.dreamprotect.a.a(a.java)`` (потому что этот метод отмечен ``@EventListener``)
Для начала, я не нашел этого мода в папке игры. Нашел bash-скриптом в 4 строки. (По неочевидным мне причинам скидывать скрипт не буду)
И вот кусочек кода этого метода (их несколько, но по вызову sha1Hex я понял, какой из них нужный)
(Заранее извиняюсь за байт-код, FernFlower не пережёвывает обфусцированный код)
```
L16 {
    aload0 // reference to self
    new cpw/mods/fml/common/network/internal/FMLProxyPacket
    dup
    aload3
    invokevirtual ru/sceri/mods/dreamprotect/DreamInfo.a()Ljava/lang/String; // <- внимание сюда
    invokestatic org/apache/commons/codec/digest/DigestUtils.sha1Hex(Ljava/lang/String;)Ljava/lang/String;
    getstatic ru/sceri/mods/dreamprotect/a.e:java.lang.String[]
    bipush 16
    aaload
    invokevirtual java/lang/String.getBytes(Ljava/lang/String;)[B
    invokestatic io/netty/buffer/Unpooled.wrappedBuffer([B)Lio/netty/buffer/ByteBuf;
    getstatic ru/sceri/mods/dreamprotect/a.e:java.lang.String[]
    iconst_1
    aaload
    invokespecial cpw/mods/fml/common/network/internal/FMLProxyPacket.<init>(Lio/netty/buffer/ByteBuf;Ljava/lang/String;)V
    putfield ru/sceri/mods/dreamprotect/a.a:cpw.mods.fml.common.network.internal.FMLProxyPacket
    iload4
    ifeq L23
}
```
В примере кода выше я отметил вызов этого метода:
```public native String a();```
Учитывая краш-репорт и всю информацию, привёдённую выше, можно с достаточной уверенностью говорить, что этот метод вернул null, и передал его в sha1Hex, где произошла ошибка.
К сожалению защита лаунчера не позволяет подключить отладчик, так что на этом мои полномочия всё.

При этом внутри файла мода я не нашел ни одного *.so файла, что указывает на то, что у этого метода нет нативной имплементации.
А даже если и есть - это баг. Этот метод не должен возвращать null.

Хотя, похоже, что имплементация есть, но только на windows.
Вероятно, это ``natives/drptct.dll`` и ``natives/drptct64.dll``
Аналогичных файлов *.so не обнаружено.
```
HBEunit@kubuntu:~/.minecraftlauncher/Dreamfinity/updates/Spacecross$ find . -name drptct*
./natives/drptct64.dll
./natives/drptct.dll
```
Возвращаясь к другим диструбтивам: ошибка произойдет и на них, ведь нет необходимой нативной библиотеки.
Кратко: не хватает нативных библиотек.

Варианты решения: 
* Компиляция библиотек под Linux (рекомендуемый способ)
* try-catch вокруг кода с ошибкой

**Comment by HBEunit** [comment]
@Noire86 я не могу переоткрыть эту issue, но я приложил некоторую полезную информацию в сообщении выше

**Comment by Noire86** [comment]
udev имеется в системе?

**Comment by Noire86** [comment]
#101 Такая же проблема, но она решилась. Игрок зашел на сервер, но в ишшуй, увы не ответил, как он это решил.

В его логе он ссылается на те же классы, и неоднократно упоминалось отсутствие /udevadm

**Comment by HBEunit** [comment]
Udev имеется

```
$ sudo apt list | grep udev
...
udev/groovy-updates,now 246.6-1ubuntu1.2 amd64 [установлен]
udev/groovy-updates 246.6-1ubuntu1.2 i386
```
udevadm нет в /sbin, но он обнаружился в /bin
```
$ ls /bin | grep udevadm
udevadm
```

**Comment by HBEunit** [comment]
```[01:02:12] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.io.IOException: Cannot run program "/sbin/udevadm": error=2, Нет такого файла или каталога```
Бинго. Иду делать симлинк

**Comment by HBEunit** [comment]
Конгратс мне
Команда ``sudo ln -s /bin/udevadm /sbin/udevadm`` решила проблему. Клиент запустился, но не может подключиться к серверу. Может быть сервер упал, однако это уже совсем другая история (С)

**Comment by HBEunit** [comment]
А я пытался
* Написать свою ФС, которая бы вместо проблемного мода подставляла пустышку, а лаунчеру прикидывалась нормальной ФС без подвохов - слишком сложно, не осилил
* Написать ту самую библиотеку - написал, скомпилировал, подключил, запустил - kernel panic
* Запустить из-под wine - ``Exit code -1073741819`` без других сообщений

А надо было в логи глянуть))

**Comment by Noire86** [comment]
Да, все было достаточно просто
Будет ли сложно сделать однокнопочное решение для подобных проблем?

Или пошаговый гайд?

**Comment by HBEunit** [comment]
> Будет ли сложно сделать однокнопочное решение для подобных проблем?
Ну не то что бы однокнопочное.. кнопок 10 нажать придется
В терминал ``sudo ln -s /bin/udevadm /sbin/udevadm`` и ввести пароль
Вообще так делать неправильно, но у меня ошибок вроде не было.
