### ISSUE TITLE
Кривой лут у теней

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#57]
**Информация:** 
- Игровой ник: jammer312
 - Сервер: Техна

**Описание бага:**
Фантомы (тени?) (невидимые мобы в незере, которые спамят черными частицами для обозначения своего присутствия) иногда дропают кристаллы душ, при этом примерно 1/5 из них имеет дополнительный суффикс ':1' в айди (8493:1 вместо 8493), из-за чего они по сути бесполезны (крафты, которые должны для них работать, не работают). Скорее всего опечатка где-то в конфигах. Хз, может, это дроп с какого-то из именованных вариантов.

**Воспроизведение:**
1. Постройте ферму фантомов в незере
2. Нафармите фантомов, чтобы выпало достаточное число кристаллов душ
3. ????
4. PROFIT (с большой вероятностью 1/5 кристаллов бесполезна. Для того, чтоб просто было их отличать, можно их прятать в ящик из термалки (который умеет много предметов одного типа хранить), ибо неправильные кристаллы не влезут в один ящик с правильными)

**Дополнительный контекст:**
Кривые конфиги?

**Comment by Noire86** [comment]
Можно скринов и рецепты, где эти кристаллы используются?

**Comment by jammer312** [comment]
![image](https://user-images.githubusercontent.com/3525275/103170957-6775e180-4859-11eb-81a2-c9603d0bae44.png)
Рецепты

**Comment by jammer312** [comment]
![image](https://user-images.githubusercontent.com/3525275/103170966-7492d080-4859-11eb-9d65-964bed2d8947.png)
Кривой кристалл

**Comment by jammer312** [comment]
![image](https://user-images.githubusercontent.com/3525275/103170992-a146e800-4859-11eb-88e5-d02bfdc7230c.png)
Прямой кристалл

**Comment by jammer312** [comment]
Если вдруг, на варпе netherfarm2 есть ящики и с правильными, и с неправильными кристаллами

**Comment by Noire86** [comment]
Спасибо, будем копать.

**Comment by Noire86** [comment]
Исправлено (вроде бы)
