### ISSUE TITLE
Фракции и френдлифаер

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#58]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна
 
**Описание предложения:**
Сделать флаг френдлифаера изменяемым (флаг фракции)

**Обоснование:**
Во-первых, я банально не вижу причин тому, что френдлифаер вообще выключен, как и тому, что его нельзя включить.
Тем же спаррингом с сопартийцем хрен займешься.
Во-вторых, эта хрень распространяется не только на игроков. Как пример, пч*о*лы: 
![image](https://user-images.githubusercontent.com/3525275/103166237-25d14080-4831-11eb-8c9f-62a2379eab39.png)
Мне норм, если они меня кусают. Мне **не** норм, если они спамят чат. И вырубить этот спам в чат я не могу, т.к. флаг френдли фаера неизменяем.

**Comment by Noire86** [comment]
Вся проблема френдлифаера в том, что было 1488 случаев, когда наивный дурачок включал френдлифаер, и его нечистые на руку "сотоварищи" просто мочили дурачка по кд и ливали с клана.

Тут могу помочь просто частной выдачей пермишена на френдлифаер.

Closed
