### ISSUE TITLE
Чатбот агрится на автоматические сообщения

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#59]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна

**Описание бага:**
Чатбот агрится на автоматические сообщения

**Воспроизведение:**
Шаги к воспроизведению бага:
1. Накатайте сообщение в лс размером хотя бы на 3 сообщения и чтоб было хотя бы 3 слова (чтоб 3мя сообщениями отправило)
2. ?????
3. ?!??!
4. Прекрати флудить!

**Скриншоты:**
![image](https://user-images.githubusercontent.com/3525275/103173418-ea079c80-486b-11eb-8479-deb668ceefc7.png)

**Comment by Noire86** [comment]
Це не баг, а фича. Отправляется несколько сообщений мгновенно - что расценивается как флуд.

**Comment by Extegral** [comment]
@Noire86, теоретически это можно пофиксить небольшим изменением логики работы таббичата, переложив ответственность за разбиение сообщений с клиента на сервер
