### ISSUE TITLE
Баг с телепортом в пустоту ( не то, о чем вы подумали)

### ISSUE THREAD

**Issue by DarkLorianPrime** [Dreamfinity/Dreamfinity-Tracker#6]
На спейсе, при написании /home или телепорте, не важно. Если есть блок воздуха, то тебя выкидывает с кора. Предложили поставить ему нулевую плотность (хз че это)

**Comment by Noire86** [comment]
Сделал телепорты /home не безопасными (без проверки), рекомендую проверить

**Comment by Noire86** [comment]
Не получится поменять механику, так как телепортирует и проверяет плагин Essentials.
