### ISSUE TITLE
Випка не решает вопрос с чатом

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#60]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна
 
**Описание предложения:**
Сделать что-нибудь с очень долгим кулдауном меж сообщениями, хотя бы ту же команду для перепосыла забракованного по рейтлимиту сообщения (скрин ниже). У меня идолка, и мне все еще режет сообщения, которые я быстро пишу, и меня это все еще бесит

**Обоснование:**
![image](https://user-images.githubusercontent.com/3525275/103173645-4fa85880-486d-11eb-9ef2-bfaf145690dd.png)

**Comment by Noire86** [comment]
Сделал игнор кулдауна от идола и выше. Просьба проверить, потом сделаю анонс в группе и сайте.

**Comment by jammer312** [comment]
Вроде работает.
