### ISSUE TITLE
Вайп энда кривой

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#61]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна

**Описание бага:**
Вайп края нынче автоматически триггерится (с задержкой в полтора часа) при смерти дракона, что хорошо, т.к. в крае редкий и необходимый ресурс.
НО
При вайпе часть чанков остаются нетронутыми, в частности, дракон может не заспавниться. Что означает, что автоматический вайп не запустить.

**Воспроизведение:**
Шаги к воспроизведению бага:
1. Запустите ручной вайп края, ибо дракон уже проебался.
2. Убейте дракона
3. Подождите полтора часа, пока край не вайпнется
4. Если дракон заспавнился, повторите 2, иначе 5
5. Дракона нема, автоматического вайпа нема.

**Ожидаемое поведение:**
Вайпался бы весь остров (или весь край) (но лучше только остров, т.к. край нужен для работы некоторых пчел, и перестраивать пасеки каждые полтора часа как-то уныло).

**Скриншоты:**
![image](https://user-images.githubusercontent.com/3525275/103307779-ff262c00-4a21-11eb-9eab-c11be436eb52.png)
![image](https://user-images.githubusercontent.com/3525275/103307792-064d3a00-4a22-11eb-9264-b2010f485525.png)

**Дополнительный контекст:**
На скринах можно увидеть торчащие обсидиановые колонны, из которых по границе чанка вырезаны куски, + то же самое с светом от прошлого портала из края (или от улья, хз)
До кучи он регенится по тому же сиду, что значит, что можно один раз спалить месторождения руд, и дальше выкапывать их в том же месте.

**Comment by Noire86** [comment]
Проблема плагина, решается полной ручной очисткой мира по запросу игроков
