### ISSUE TITLE
Фракции и френдлифаер 2

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#62]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна

**Описание бага:**
Флаг френдлифаера у фракции врублен, сам френдлифаер вырублен.

**Воспроизведение:**
Шаги к воспроизведению бага:
1. Засеттите флаг френдлифаера для фракции
2. Поставьте пасеку с агрессивными пчелами и сядьте рядом
3. ...
4. You can't hurt members in your faction

**Ожидаемое поведение:**
Пчелы должны объедать мясо с костей и просить еще. И точно не должны спамить в чат.

**Скриншоты:**
![image](https://user-images.githubusercontent.com/3525275/103309797-1e738800-4a27-11eb-9f30-cdb445416e80.png)
Делалось в незере, где приватов нет (незеровские пчелы агрессивные по дефолту (sinister, fiendish, demonic))

**Comment by Noire86** [comment]
Скорее всего пчОлы работают от имени фейкплеера - либо же от имени вас самих, и таким образом вы бьете себя самостоятельно. Такова уж механика работы фикса.

**Comment by Noire86** [comment]
К слову, могу отключить эту механику, и пчОлы уже будут дамажить все и вся.

**Comment by jammer312** [comment]
> К слову, могу отключить эту механику, и пчОлы уже будут дамажить все и вся.

Наверное, так лучше будет.
Про "дамажить от имени вас самих" - если стрельнуть из лука в небо и встать под падающую стрелу, урон пройдет. Так что хз, почему пчелы, дамажащие от имени игрока, не могут его дамажить.

**Comment by Noire86** [comment]
Если пч0лы будут абьюзится - то фикс снова включу. Закрыто.
