### ISSUE TITLE
Кремний из проект реда не крафтится

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#63]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна

**Описание бага:**
Кремний прожект реда крафтится через распиливание какой-то хрени алмазной пилой, и используется в различных схемах из прожект реда (мне нужна state cell, к примеру, для нее нужен красный кремний, который делается из обычного). При этом пила **не крафтится**

**Скриншоты:**
![image](https://user-images.githubusercontent.com/3525275/103312091-13bbf180-4a2d-11eb-896f-93bddc9b0b2a.png)

**Comment by Noire86** [comment]
Кремний покупается у НПС.
