### ISSUE TITLE
/mail trades

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#65]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна
 
**Описание предложения:**
/mail trades (команда) недоступна игрокам.
Команда выводит список текущих сделок (то же, что каталог, но без возможности автоматического создания письма).
Собственно, предложение спилить с нее ограничение доступа.

**Обоснование:**
А зачем ее вообще отобрали?

**Comment by Noire86** [comment]
Ее не отбирали, скорее всего команды работающие с форджевыми пермишнами плохо работают с пермишнами баккита.
