### ISSUE TITLE
Эффект реанимации (спектральные пчелы) не работает

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#67]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна

**Описание бага:**
В названии тикета по сути все передано. Трейт пчел на реанимацию (от спектральных пчел, предпоследних пчел, которых вообще можно вывести) не работает.

**Воспроизведение:**
Шаги к воспроизведению бага:
1. Запилите спектральных пчел и убедитесь, что они активны
2. Накидайте им костей, гнилой плоти или палок ифритов
3. ...
4. Нихуя! Трейт не работает.

**Ожидаемое поведение:**
Из костей должны спавниться скелеты, из плоти - зомби, из палок ифритов - ифриты.

**Comment by Noire86** [comment]
Этот эффект (Ressuration) выключен по дефолту во избежание заспамливания мобами.

Можно включить, но стоит ли?

**Comment by jammer312** [comment]
Хз, я его ни разу в деле не видел. Если он спамит мобами значительно быстрее проклятой земли, то, может, включать не стоит.
Имхо если не включать, то стоит заблэклистить (через конфиг форестри, по идее он уберет мутацию в них, при этом тот же неи не будет ее показывать) этих пчел (спектральных и фантомных (эффект у фантомных тоже ведь вырублен?)), ибо выводить их лютый гемор, при этом единственная причина их выводить - чтоб добраться до этого эффекта (ну или где-нибудь явно сказать, что эффект не работает, чтобы это не было сюрпризом).

**Comment by Noire86** [comment]
Думаю что оставим выключенным, чтобы не гадать в случае чьих-то хитрожопых действий.
