### ISSUE TITLE
Баг с роботами из ОПЕНКОМПЬЮТЕРСА и АЕ2

### ISSUE THREAD

**Issue by DarkLorianPrime** [Dreamfinity/Dreamfinity-Tracker#7]
При взаимодействии робота и АЕ2 происходит краш. По словам игроков

**Comment by Noire86** [comment]
Попробуй воспроизвести и скинуть логи текстом

**Comment by Noire86** [comment]
@DarkLorianPrime  нужна инфа

**Comment by DarkLorianPrime** [comment]
За неимением док-в - закрываю.
