### ISSUE TITLE
Карьеры и шахтеры

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#70]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна
 
**Описание предложения:**
Если кратко, то суть предложения - разнерфать эндер карьер и сделать миром, в котором им разрешено копать, не овер, а дип дарк (или, как вариант, оба)

**Обоснование:**
Сначала про "разнерфать карьер". У карьера две фишки, которые делают его лучше цифрового шахтера. Первая - возможность копать на практически неограниченной площади, не генерируя при этом лагов (отчасти из-за отсутствия блок апдейтов, отчасти из-за того, что он прогружает всегда только два чанка, где сам сидит и где копает). Вторая - то, что он прогружает себя, пока копает. Здесь обе эти фишки успешно убиты, т.к. область раскопок меньше, чем у шахтера (максимальная - 63х63, когда у шахтера 65х65), а то, что он прогружает себя, на такой малой области по сути роли и не играет (ибо тот же шахтер может за несколько минут все нужные руды (иррадий, энергий, этерний) выкопать со всей области раскопок; в случае с карьером значительная часть этого времени уйдет на его развертку).
Ну и на деле получается карьер, который стоит (с максимальными апгрейдами) как несколько шахтеров, копает медленно, копает всякий мусор, и имеет меньшую область действия, чем шахтер. По сути единственный стимул его крафтить - чтобы использовать его как чанклоадер (для этого даже апгрейдов делать не нужно, по сути примерно как шахтер и выходит по цене).

Про дип дарк: этот мир по сути никто не использует ни для чего, кроме как для добычи ресурсов. Почему бы не разрешить пользовать в нем карьеры и шахтеры, чтоб вместо овера дырявили побочный мир (который и вайпнуть не жалко в случае чего)? Особенно шахтеры, которые (если без заморочек со стороны игрока) за собой оставляют тыщу дыр, которые потом спавнят мобов и лагают.

**Comment by Noire86** [comment]
Весь негатив карьера - в чанклоадинге и огромных дырах по миру. Выхлопа от него немного, а его прогрузкой можно очень легко положить сервер, располовинив прогрузкой какую-нибудь йоба-машину.

Дип дарк фентезис не нужен, потому что это еще один допмир в котором будут чанковые нагрузки, еще и постоянные, без более менее нормальной возможности отследить положение лагмашины и ее принадлежности.

**Comment by Extegral** [comment]
> Дип дарк фентезис не нужен

@Noire86, я понимаю что у тебя психологическая травма ещё с детства, но не мешай другим людям из-за этого предлагать и делать правильные вещи, пожалуйста.

**Comment by Noire86** [comment]
Ну сделайте, и наткнетесь на то же самое, я ж не против

**Comment by Noire86** [comment]
Тикет закрою.
