### ISSUE TITLE
Апгрейд труб из экстраутилитис на взаимодействие с миром частично не работает

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#72]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна

**Описание бага:**
В описании апгрейда сказано, что если нацепить его на трансфер ноду предметов, которая прикреплена к блоку булыги, рядом с которым источники лавы и воды, нода начнет генерировать булыгу. Этого не происходит

**Воспроизведение:**
Шаги к воспроизведению бага:
1. Запилить предложенную в описании апгрейда (2 страница в неи) схему
2. Увидеть, что булыга не генерируется.
 
**Ожидаемое поведение:**
Булыга должна генерироваться. Хз, что там с fairly quickly, но хоть как-то.

**Скриншоты:**
![image](https://user-images.githubusercontent.com/3525275/103586737-c2ad7100-4ef6-11eb-8511-bd139afa40af.png)

![image](https://user-images.githubusercontent.com/3525275/103586678-a4477580-4ef6-11eb-8f5d-8c470fcfa205.png)

**Comment by Noire86** [comment]
АВЧОМСМЫСОЛ? В термале есть удобный и быстрый крафтер булыги. Есть видео нормальной работы этого генератора из экстраутилит?

**Comment by Extegral** [comment]
> АВЧОМСМЫСОЛ? В термале есть удобный и быстрый крафтер булыги. Есть видео нормальной работы этого генератора из экстраутилит?

СМЫСОЛ в том, что генератор из утилит намного быстрее и создаёт меньше нагрузки на сервер, вот в чём смысол. Он должен работать.

**Comment by Noire86** [comment]
Исправлено
