### ISSUE TITLE
Пчела пропала прям из рук

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#73]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна
 
**Описание потерянного:**
Одна пчела-принцесса пропала прямо из рук (переносил ее из одного слота инвентаря в другой, и прям при переносе пропала).

**Обстоятельства потери:**
Примерно около 16:09 (UTC+3) наведался на свою пасеку, где селекцией занимаюсь, достал пчел из двух пасек и стал их сканировать с помощью ручного сканера пчел, после скана второй принцессы решил переместить ее в другой слот, она внезапно пропала.

**Дополнительный контекст:**
Возвращать ничего не нужно, ибо у меня бэкапы пчел есть + восстанавливать метадату наверняка будет лютым гемором.
В логах клиентских ничего подозрительного нет.
Пропавшая пчела - принцесса, причем pristine (т.е. из-за старости пропасть не могла, да и не в инвентаре оно происходит, а при генерации нового поколения).
Из инвентаря выпасть не могла, ибо удалятор прошелся до того, как я вообще к пасеке пришел, и я перезашел на сервер, чтобы проверить, что это не клиентские глюки, и пчелу так и не нашел.
Tldr; хз, что это вообще было, гляньте логи сервера, может, там что интересное есть.

**Comment by Noire86** [comment]
Включен инвентори твикс? Он любит обнулить предметы с изменяющимися метадатой и нбт

**Comment by Noire86** [comment]
Тикет закрою.
