### ISSUE TITLE
Mcmmo не работает с инструментами из нестабильного металла

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#74]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна

**Описание бага:**
Речь об инструментах из extra utilities.
Копание киркой не качает шахтерство, копание лопатой не качает раскопки, меч не качает обращение с мечами etc.

**Comment by DarkLorianPrime** [comment]
mcmmo вообще плохо взаимодействует с предметами из других модов.

**Comment by jammer312** [comment]
С тинкером нормально взаимодействует (если не считать топоров, которые пытаются убить хозяина).

**Comment by DarkLorianPrime** [comment]
Дай айди предметов которые не работают, их можно будет попробовать закинуть в конфиг

**Comment by jammer312** [comment]
Кирка - 8512
Лопата - 8498
Топор - 8496
Меч - 5830 и 8499
Мотыга - 8564

**Comment by DarkLorianPrime** [comment]
Инструменты добавлены.
