### ISSUE TITLE
Телепортационная пластина и ядро корабля

### ISSUE THREAD

**Issue by HeroBrine1st** [Dreamfinity/Dreamfinity-Tracker#76]
# Информация
 - Игровой ник: ``Adisman``
 - Сервер: ``Spacecross``

# Описание бага
После прыжка корабля телепортирующие пластины (``ThermalExpansion:Plate 6``) не обновляют свои точки телепортации, оставляя их на своем прошлом месте. Кроме этого, убрать такие точки невозможно (у меня одна такая уже второй день есть - перезагрузки не помогают).

# Воспроизведение
Шаги к воспроизведению бага:
1. Установить телепортирующую пластину на корабль и настроить на ней точку телепортации, чтобы на пластину можно было телепортироваться.
2. Прыгнуть на корабле внутри одного измерения.

Затем можно эксплуалатировать:

1. Установите на другой пластине телепортацию на точку, полученную ранее вышеописанным способом
![изображение](https://user-images.githubusercontent.com/22197536/104106321-dc1f3600-52c5-11eb-90a2-f945bc476c8e.png)
2. Встаньте на пластину и телепортируйтесь ровно в никуда. Скриншот сделан сразу же после телепортации, без движений и уничтожения блоков; булыжник был установлен мной ранее для удобства, без него оно бы телепортировало ровно на ту же точку.
![изображение](https://user-images.githubusercontent.com/22197536/104106362-21dbfe80-52c6-11eb-9b08-3d6111d30271.png)

# Ожидаемое поведение
При прыжке с пластиной; варианты:
* Точка телепортации просто удаляется, пластина становится деактивированной
* Точка телепортации переносится вместе с пластиной

При телепортации на невалидную точку:
* Телепортация отменяется, точка удаляется, возможно краш сервера ¯\\\_(ツ)\_/¯

# Дополнительно
Игрок ``Wistaf`` так же встретил этот баг. Его точка телепортации называется ``kor`` и является приватной.
Прошу удалить его точку ``kor`` и мою точку ``123`` из списка телепортации :-)
Ну, если возможно, так-то не мешает.

P.s. немного изменил разметку для лучшей читаемости, не бейте.

**Comment by Noire86** [comment]
Ну это механика мода, автор же не предполагал что пластины будут перемещаться в пространстве и времени, поэтому не предусмотрел обновление координат фактического нахождения пластины (что плохо)

**Comment by Noire86** [comment]
Тикет закрою, так как это нормальное поведение мода
