### ISSUE TITLE
Деревья форестри и топоры

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#78]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна

**Описание бага:**
Большие топоры из тинкера и атомный разборщик из меки некорректно срубают деревья из форестри. Конкретно ломаются все блоки, но выпадает только один.

**Воспроизведение:**
1. Запилите любое дерево из форестри
2. Срубите его большим топором из тинкера (который рубит все дерево сразу) или атомным разборщиком в режиме жил
3. ...
4. Срубится все дерево, выпадет только один блок.

**Ожидаемое поведение:**
Очевидно, должно либо не срубаться все дерево (емнип топоры тинкера вообще не считали деревья из форестри за деревья, так что наверняка тут пытались это пофиксить, но в процессе налажали), либо выпадать все срубленные блоки (точнее, выпадать все срубленные блоки и так и так должны).

**Comment by Noire86** [comment]
Все еще актуально?

**Comment by Veritaris** [comment]
Деревья из forestry представляют собой довольно отличную от обычных деревьев сущность. Я бы советовал использовать для добычи древесины обычный топор или же ферму
Закрыто
