### ISSUE TITLE
Каменелый мультибаг

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#79]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна

**Описание бага:**
В пистрониксе есть стрелы, жертвы которых обращаются в статуи.
Если убить такой стрелой визера, то с него выпадет статуя, но с этой статуей сразу две проблемы:

1. Статуя копирует визера в момент смерти. Т.е. в упавшем на бок состоянии. Ну и с светящейся аурой, как же еще.
2. Любой, кто видит эту статую, видит индикатор хп босса (пустой). В том числе, когда она в инвентаре (другие игроки видят статую в инвентаре игрока лишь тогда, когда ее берут в руки) (ну или если дать в руки манекену). Все бы ничего, но оно запоминает имя моба.

**Воспроизведение:**
Шаги к воспроизведению бага:
1. Убейте визера окаменяющей стрелой (petrifying arrow)
4. Узрите!

**Ожидаемое поведение:**
Хз, хочу не упавших визеров. Опционально чтоб не было индикатора хп.

**Скриншоты:**
![image](https://user-images.githubusercontent.com/3525275/104488934-19463980-55e0-11eb-8f0d-ba29f1cb1cea.png)

**Дополнительный контекст:**
Кстати, пистроникс на сервере только ради статуй? Пистоны то в привате не работают.

**Comment by jammer312** [comment]
Лол, если смотреть в сторону такой статуи, небо темнеет (прям как с обычным визером)

**Comment by Noire86** [comment]
Лол, пистоны не пашут в приватах? Разве?

**Comment by jammer312** [comment]
Я некоторое время назад тестил, не работали. Именно пистоны пистроникса. Вне привата ровно такой же механизм работал

**Comment by Veritaris** [comment]
Полагаю, это связано с тем, что статуи являются сущностями с измененными параметрами и скином. Думаю, если убить любого другого моба, который изменяет форму (крипер, дракон края, эндермен с блоком в руках), то они будут в таком виде, как в момент смерти

**Comment by Noire86** [comment]
Это уже скорее к автору мода, чем к нам. Если пистоны работают в привате, то уже хорошо. Тикет закрою.
