### ISSUE TITLE
Скины армореда выпадают как лут, когда не должны

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#80]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна

**Описание бага:**
Скины из aurmourer's workshop выпадают с игроков, с которых не выпадает инвентарь (при смерти).

**Воспроизведение:**
Шаги к воспроизведению бага:
1. Убейте донатера со скином
2. Скины выпадут, голова дропнется, остальной инвентарь останется у донатера.

**Ожидаемое поведение:**
Наверное, дропаться не должны.

**Дополнительный контекст:**
Хз, почему это не зарепортил Prtsscout, который так с этого горел, походу многие до гитхаба банально не добираются.

**Comment by Noire86** [comment]
Ну так выпадение скинов - заложенная механика арморера. Это конечно можно выключить, если не ошибаюсь

**Comment by BochkaDeyalo** [comment]
Нет, это является проблемой. С донатногоперсонажа ничего выпадать не должно, как таковое. Забить на проблему - не является её решением.
