### ISSUE TITLE
Мобы спавнятся в приватах

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#81]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна

**Описание бага:**
Баян, но, может, кто-нибудь когда-нибудь таки решит его пофиксить.
Мобы из модов (например, элементали из термалки и слаймы из тинкера) игнорируют флаг запрета спавна монстров (который по умолчанию стоит в приваченных чанках).
Вроде как распространяется на буквально всех не-ванильных враждебных мобов.
Также распространяется на мобов, которых спавнит проклятая земля.

**Ожидаемое поведение:**
Запрет на спавн монстров должен запрещать спавн всем мобам, а не только ванильным.

**Comment by Noire86** [comment]
Есть возможность проверить еще каких-то мобов? Потому что тут чтобы пофиксить, придется страшно изъебнуться, потому что у плагина фракций свои алгоритмы запрета. А если в модах спавн делается как-то по своему, то тут траблы.

**Comment by Noire86** [comment]
Проблему не решить неинвазивными методами
