### ISSUE TITLE
Запилить защиту мобов в приватах

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#82]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312 
 - Сервер: Техна
 
**Описание предложения:**
Сделать запрет на пвп в привате распространяющимся не только на монстров против игроков и игроков против игроков, но еще и на игроков против мобов (либо всех, либо нейтральных и дружелюбных) (кроме игроков, которые могут строить в привате) и мобов против мобов.

**Обоснование:**
Потому, что логично запретить игрокам, которых даже не можешь убить, не включив пвп в своем привате, вырезать домашний скот и жителей.
Про мобов против мобов - это защита от чуть более изощренного грифа, вроде запуливания с помощью молота на отдачу зомбей в загон с жителями, ну и оно логично, ибо сейчас запрет на пвп также является односторонним запретом на пве (запрещает монстрам дамажить игроков).

**Comment by Noire86** [comment]
В факшнсе мобы вроде защищены по дефолту. Разве чужой игрок может выпилить мобов в привате?

**Comment by jammer312** [comment]
Да, может. Мне выпиливали жителей, я выпиливал коней, не вижу причин этому не работать со всеми остальными.

**Comment by Noire86** [comment]
Странно, я как то даже не думал об этом. Надо узнать защищает ли вообще факшнс мобов

**Comment by Noire86** [comment]
В Factions защиты мобов, увы нет. Доп. плагинов я не нашел.
