### ISSUE TITLE
Заменить /warp и /home нормальными аналогами

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#83]
**Информация (укажите соответствующие данные):**
 - Игровой ник:  jammer312
 - Сервер: Техна (да и по сути все сервера)
 
**Описание предложения:**
Заменить телепортирующие команды (/warp, /home, /back) аналогами, в которых нет костылей, запрещающих телепортирование. Либо, как вариант, добавить нормальные аналоги, чтобы можно было по тем же координатам телепортироваться без всяких смещений и отказов.

**Обоснование:**
Текущие реализации имеют костыли, которые запрещают телепорт в определенных случаях. Все бы ничего, но эти костыли реализованы настолько ущербно, что от них вреда больше, чем пользы.
Например, на спейсе если у тебя на корабле есть воздух, то без багоюза ты на этот корабль не телепортируешься, ибо хомка какого-то хера считает воздух за твердый блок, и из-за встроенных костылей телепортирует на ближайшее свободное от воздуха место, т.е. за обшивку корабля, и удачи добираться до воздуха до того, как помер. И это при условии того, что оно найдет такое место (вроде радиус поиска ограничен), иначе удачи добираться до корабля (вообще, может, за последние месяц-два это исправили, но что-то мне подсказывает, что нет).
Ровно из-за того же на техне на спавне посреди асфальта стоит блок обсидиана. Ибо встроенные в варп костыли считают не-ванильные блоки лавой или жидкой смертью или еще чем, в любом случае, телепортировать на них ну ни в коем случае нельзя, поэтому телепортируют на ближайший ванильный блок, над которым хотя бы два блока свободны от ванильных блоков. Да, в том числе в не-ванильные блоки. И, опять же, это при условии, что оно найдет такой блок.
Отдельная тема с /back и частными случаями установки хомки. Летишь такой над пустотой куда-нибудь, потребовалось телепортироваться куда-то. Пытаешься вернуться через /back - иди нахер, дырка в полу.

И это лишь очевидный вред. Ровно те же костыли в /warp могут быть использованы еще и для того, чтобы ходить сквозь стены там, где возможности это сделать быть не должно. Например, в приватах игроков.

Я, конечно, понимаю, что были жалобы от игроков, которые по своему невежеству засирали хомки блоками и дохли из-за этого, но не повод же это так уродовать функционал этих команд.

**Comment by jammer312** [comment]
Вообще, с варпами, особенно публичными, может и стоит эти костыли оставить. Но таки запилить вариант, который будет нормально телепортировать.
Или, как вариант, вместо телепорта не туда, куда надо, писать БОЛЬШИМИ КРАСНЫМИ БУКВАМИ нечто вроде "варп опасен, повторите команду, чтобы все равно туда телепортироваться", и при повторе команды в ближайшие полминуты таки телепортировать куда надо.

**Comment by Noire86** [comment]
Я лично не встречал никаких проблем с безопасными телепортами эссеншлса. Он работает немного иначе насколько я знаю, он проверяет наличие ХОТЬ КАКОГО либо блока в округе под ногами, и свободное место (воздух).

То есть единственная проблема здесь - это кастомные блоки воздуха, ты прав. Но я еще ни разу не столкнулся с тем, чтобы на спавн или правильно поставленный варп как-то криво телепортнуло. Тут еще есть шансы рассинхрона, и тебя правда можно наполовину в блоке заспавнить. Но это не так часто.

**Comment by Noire86** [comment]
Фиксить это возможным не представляется, все плагины баккита на варпы и тп действуют одинаково. Делать форджмод тоже накладно - ибо не работают пермишны.
