### ISSUE TITLE
Рецепты в дуговой печи из иммерсива и их автоматизация

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#85]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна
 
**Описание предложения:**
Убрать у дуговой печи иммерсива возможность плавить металлическую пыль в слитки.
Либо, как вариант, сделать в дуговой печи явное разделение входов (левый для плавящегося, правый для примесей, как и в гуи), что, впрочем, сложнее.

**Обоснование:**
Дуговая печь может, помимо всего прочего, плавить сплавы, при этом все так же жрет много энергии, но позволяет получать результат быстро и массово. Но с некоторыми сплавами, конкретно теми, которые используют металлическую пыль в качестве примеси, есть проблема: их не получается нормально автоматизировать, так как оба входа сверху от печи ведут в один и тот же инвентарь, и металлическая пыль, которая должна быть примесью, попадает не в слоты примесей, а в слоты плавящегося. Один из вариантов решения - убрать все рецепты, в которых металлическая пыль не является примесью, чтобы она могла попадать только в слоты примесей.

**Comment by Veritaris** [comment]
Разве в один и тот же? Насколько я знаю (и сам этим пользовался), если пользоваться конвейерами из этого же мода, то, если стоять лицом к печи, вход слева ведёт в инвентарь для плавки, вход справа - в инвентарь для примесей
