### ISSUE TITLE
Кремний не покупается у нпц

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#87]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна

**Описание бага:**
На /warp shop есть только два нпц-торговца, один торгует прессами, второй небесным камнем. Кремний там не купить.

**Ожидаемое поведение:**
Ожидается возможность купить кремний, т.к. он не крафтится (рецепт есть, но одна из компонент - алмазная пила, не крафтится #63)

**Скриншоты:**
![image](https://user-images.githubusercontent.com/3525275/104833286-7d9b1e80-58a8-11eb-9b24-a77535b8ba4a.png)
![image](https://user-images.githubusercontent.com/3525275/104833300-a7544580-58a8-11eb-9e2b-138d2c4d92d0.png)
![image](https://user-images.githubusercontent.com/3525275/104833306-b6d38e80-58a8-11eb-8d39-b72df2f71fa6.png)
![image](https://user-images.githubusercontent.com/3525275/104833313-bcc96f80-58a8-11eb-9c96-6b9e2c8e323a.png)

**Дополнительный контекст:**
Неплохо было бы вернуть авторам иссуев возможность переоткрывать их при преждевременном закрытии кем-либо.

**Comment by Noire86** [comment]
![2021-01-20_19 34 28](https://user-images.githubusercontent.com/9317997/105205748-a1838c00-5b56-11eb-9dcb-77e81bd41db0.png)

Добавлено
