### ISSUE TITLE
dynmap некорректно загружает головы игроков

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#88]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна (хз, может, все)

**Описание бага:**
dynmap подгружает головы игроков как картинки (хз, зачем, возможно, для чата). При этом оно не учитывает скины, и по сути подгружает одну и ту же картинку с своим названием для каждого игрока

**Ожидаемое поведение:**
Картинки голов с учетом скинов

**Скриншоты:**
![image](https://user-images.githubusercontent.com/3525275/105072829-4ccd0c00-5a97-11eb-9efd-a70c29889450.png)
![image](https://user-images.githubusercontent.com/3525275/105072890-5eaeaf00-5a97-11eb-91a3-532c85ee516d.png)

**Comment by Noire86** [comment]
Оно и не должно работать. В динмапе отключены чат и игроки
