### ISSUE TITLE
Окаменяющие стрелы создают статуи в приватах

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#89]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна

**Описание бага:**
Стрелы из пситроникса при убийстве мобов создают их статуи (блоки), при этом они создаются даже в чужих приватах, и могут в каких-то случаях заменять собой блоки, что дает возможность легкого грифа.

**Ожидаемое поведение:**
По идее статуй ставить не должны, ибо это блок как никак.

**Comment by Noire86** [comment]
Есть смысл убрать пистроникс?

**Comment by jammer312** [comment]
Хз, статуи - прикольно, но это чисто свистелка без практических применений.
Механизмы на продвинутых пистонах тоже прикольно, но по-моему их никто не делает.
¯\\\_(ツ)_/¯

**Comment by Noire86** [comment]
Подумаю о том, чтобы убрать пистроникс.
