### ISSUE TITLE
Чанклоадеры не могут прогружать чанки в измерении без игроков

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#90]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна (но на деле везде)

**Описание бага:**
Имеющийся плагин на чанклоадеры не предотвращает выгрузку чанков, когда она форсится выгрузкой измерения из-за того, что в измерении не осталось игроков. Особенно больно на спейсе, где измерений разных дофига, и если селиться не на земле и не в космосе, то чанклоадеры банально не будут работать, но в том числе актуально для техны, где есть несколько побочных измерений, где можно жить.

**Ожидаемое поведение:**
Чанклоадер должен предотвращать выгрузку измерения и чанка.

**Comment by IteratorW** [comment]
По идее это зависит от меня, как только я пофикшу мелкий баг в своем плагине и его можно будет поставить на сервера, проблема исчезнет.
Не знаю когда будет время этим заняться, возможно на этой неделе.

**Comment by Noire86** [comment]
@IteratorW ну че там с чанками, как дела обстоят?

**Comment by IteratorW** [comment]
> @IteratorW ну че там с чанками, как дела обстоят?

нашел место спросить, лул. я хз когда снова смогу взяться за таски, мб я выбрал не то время чтобы у вас говнокодить :D
