### ISSUE TITLE
Лаунчер не запускается

### ISSUE THREAD

**Issue by makarhuyaker** [Dreamfinity/Dreamfinity-Tracker#91]
java -Dlauncher.debug=true -jar Dreamfinity.exe
GravitLauncher (fork sashok724's Launcher) Launcher v4.5.0-1 stable
License for Launcher GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
2021.01.31 17:14:30 [INFO] Restart Launcher with JavaAgent...
2021.01.31 17:14:30 [INFO] If need debug output use -Dlauncher.debug=true
2021.01.31 17:14:30 [INFO] If need stacktrace output use -Dlauncher.stacktrace=true
2021.01.31 17:14:30 [DEBUG] Testing stacktrace
2021.01.31 17:14:30 [DEBUG] Verifying class loader
2021.01.31 17:14:30 [DEBUG] Verifying JVM architecture
2021.01.31 17:14:30 [DEBUG] Restart Launcher
2021.01.31 17:14:30 [DEBUG] Commandline: [C:\Program Files\Java\jdk-15.0.2\bin\java.exe, -Dlauncher.debug=true, -Dlauncher.stacktrace=false, -javaagent:C:\Users\user32\Downloads\Dreamfinity.exe, -cp, C:\Users\user32\Downloads\Dreamfinity.exe, ru.gravit.launcher.BWcRcO5xBROX7WKEf05GyjsI]
Launcher Agent
2021.01.31 17:14:30 [DEBUG] Testing stacktrace
2021.01.31 17:14:30 [DEBUG] Verifying class loader
2021.01.31 17:14:30 [DEBUG] Verifying JVM architecture
GravitLauncher (fork sashok724's Launcher) Launcher v4.5.0-1 stable
License for Launcher GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
2021.01.31 17:14:30 [ERROR] java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngineFactory.getScriptEngine()" because "ru.gravit.launcher.lmz1NPNaT3oXGwuI4opyQdpE.nashornFactory" is null
        at ru.gravit.launcher.lmz1NPNaT3oXGwuI4opyQdpE.newScriptEngine(Unknown Source)
        at ru.gravit.launcher.rV49xsWNYQkxTRKu2m9ujUYx.<init>(Unknown Source)
        at ru.gravit.launcher.BWcRcO5xBROX7WKEf05GyjsI.start(Unknown Source)
        at ru.gravit.launcher.BWcRcO5xBROX7WKEf05GyjsI.main(Unknown Source)

**Comment by Noire86** [comment]
Почему jdk 15 версии? Нужен 8

**Comment by Noire86** [comment]
Проблема решена?

**Comment by iocmet** [comment]
Сам тогда решил и забыл написать что да...
