### ISSUE TITLE
Апгрейд редактирования табличек не может редактировать таблички

### ISSUE THREAD

**Issue by jammer312** [Dreamfinity/Dreamfinity-Tracker#93]
**Информация (укажите соответствующие данные):**
 - Игровой ник: jammer312
 - Сервер: Техна

**Описание бага:**
Апгрейд редактирования табличек, помещенный в адаптер, видит таблички, но не может их изменять (речь об opencomputers).

**Скриншоты:**
![image](https://user-images.githubusercontent.com/3525275/106669872-6012c800-65bd-11eb-8148-b49d9812eaa6.png)

**Дополнительный контекст:**
Вне привата тоже не работает

**Comment by Noire86** [comment]
В сингле работает?

**Comment by jammer312** [comment]
Сингл же не работает (на техне).

**Comment by Noire86** [comment]
Прошу прощения за долгий ответ. На отдельном клиенте с той же версией мода работает это улучшение?

**Comment by Noire86** [comment]
Если проблема с табличками не критичная - ишшуй думаю можно закрыть. Все что можем сделать со своей стороны - проверить обновления ОС для 1.7.10
