### ISSUE TITLE
Краш, по неизвестной причине

### ISSUE THREAD

**Issue by DaYundexTuxi** [Dreamfinity/Dreamfinity-Tracker#94]
**Информация :**
 TheYundexTuxi
 Technocracy

**Описание бага:**
В какой-то момент майнкрафт зависает, и крашится. Вроде бы только на базе yarik1415.

**Воспроизведение:**
Тут точных нету шагов, это может быть и прогрузка чанка(после уменьшения дистанции рендера, ничего не изменилось) или же самопроизвольный краш. Вот лог:
[crash-2021-02-03_21.04.09-client.txt](https://github.com/Dreamfinity/Dreamfinity-Tracker/files/5921021/crash-2021-02-03_21.04.09-client.txt)

**Дополнительный контекст:**
Опять же, неизвестно. Оперативной памяти выделено 5Г не думаю что проблема в этом. Большей информацией не владею.

**Comment by Noire86** [comment]
Обычная ошибка тесселяции, вас посетила магия. 

Могу посоветовать поставить рендер на default, и перекреститься три раза.

**Comment by Noire86** [comment]
Помогло, или так же вылетает?

**Comment by Noire86** [comment]
Пожалуйста, откройте новый тикет в том случае, если проблема повторяется.
